name: Deploy

on:
  push:
    branches:
      - master

# defaults:
#   run:
#     shell: bash

jobs:
  
  build:
    runs-on: ubuntu-latest
    name: Publish to Cloudflare

    steps:

      - name: Checkout
        uses: actions/checkout@main 

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'